---
abstract: 'simple bencher tool kit'
author:
  - 'Ben Hengst <notbenh@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tool-Bench
requires:
  JSON: 0
  List::Util: 0
  Mouse: 0
  MouseX::Getopt: 0
  Test::Most: 0
version: 0.001
